#!/bin/sh
# Michael Kohl <http://citizen428.net>
# 2009-08-23
DIR=`pwd`
echo "Symlinking TextMate bundle"
if [ -f ~/Library/Application\ Support/TextMate/Bundles/Clojure.tmbundle ]; then
  echo "Symlink already exists, doing nothing!"
else
  ln -s $DIR/Clojure.tmbundle ~/Library/Application\ Support/TextMate/Bundles/
  echo "Done."
fi

